name: Cleanup on PR closure

concurrency:
  group: ${{ github.ref_name }}-clean-up
  cancel-in-progress: true

permissions:
  packages: write

on:
  pull_request:
    types: [closed]

jobs:
  cimgen:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: ${{ github.repository_owner }}
          name: cimgen
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: pr-${{ github.event.pull_request.number }}
  clean-untagged:
    needs:
      - cimgen
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry with PAT_TOKEN
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete all containers from repository without tags
        uses: quartx-analytics/ghcr-cleaner@v1
        with:
          owner-type: org # or user
          token: ${{ secrets.PACKAGE_DELETE_PAT }}
          repository-owner: ${{ github.repository_owner }}
          package-name: cimgen
          delete-untagged: true
